=== oscar090132/EjecutablePresupuesto/RCLXSD/0602.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 3 (http://www.altova.com) by Jairo Marin (SINAP) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="0001.xsd"/>
	<xs:element name="movimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tipo" type="TipoC1RType"/>
				<xs:element name="rubroFuente" type="CodigoC50RType"/>
				<xs:element name="esCredito" type="BooleanB2RType"/>
				<xs:element name="valor1" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor2" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor3" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor4" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor5" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor6" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor7" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor8" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor9" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor10" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor11" type="ValorN18RType" minOccurs="0"/>
				<xs:element name="valor12" type="ValorN18RType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MovimientoRubros">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="movimiento" maxOccurs="2000"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="movimientosPresupuestales">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="movimientoPresupuestal" maxOccurs="5000"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="movimientoPresupuestal">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="vigencia" type="VigenciaN4RType"/>
				<xs:element name="tipo" type="CaracterC1RType"/>
				<xs:element name="numeroDocumento" type="CodigoC20RType"/>
				<xs:element name="tipoDocumento" type="CaracterC1RType"/>
				<xs:element name="fechaDocumento" type="xs:date"/>
				<xs:element name="documentoConpes" type="CodigoC20NType" minOccurs="0"/>
				<xs:element name="fechaDocumentoConpes" type="xs:date" minOccurs="0"/>
				<xs:element ref="MovimientoRubros" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oscar090132/EjecutablePresupuesto/ADC.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<movimientosPresupuestales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="0602.xsd">
<version>4.1.1</version>
<movimientoPresupuestal>
<vigencia>2018</vigencia><tipo>A</tipo><numeroDocumento>034</numeroDocumento><tipoDocumento>D</tipoDocumento><fechaDocumento>2018-04-12</fechaDocumento>
<MovimientoRubros>
<movimiento>
<tipo>I</tipo><rubroFuente>111201020187-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>6000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>87715520</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>121001110001-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>7000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>683702523</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>122001080001-0134</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>17000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020001-0002</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>92319256</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020002-0003</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>187316</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020003-0004</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>140485</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020004-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>266616005</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020005-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>163563344</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124010020006-0006</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>9552833</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>124100000003-0016</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>18000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>I</tipo><rubroFuente>310100010003-0008</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>51591118</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32121010003-0130</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>25000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32011020002-0006</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>9552833</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32111010001-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>16500000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32111010008-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>78563344</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32111010004-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>30000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32091010003-0002</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>20000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32091010001-0002</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>72319256</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32041010018-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>20000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32041010019-0016</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>18000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32011010012-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>6000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32041010001-0004</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>140485</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>31200011501-0099</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>10000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32011010010-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>20000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>31300060001-0134</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>3000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32031010001-0003</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>187316</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32031010002-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>12116005</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
<tipo>E</tipo><rubroFuente>32143010002-0005</rubroFuente><esCredito>true</esCredito><valor1>0</valor1><valor2>0</valor2><valor3>0</valor3><valor4>58000000</valor4><valor5>0</valor5><valor6>0</valor6><valor7>0</valor7><valor8>0</valor8><valor9>0</valor9><valor10>0</valor10><valor11>0</valor11><valor12>0</valor12>
</movimiento>
<movimiento>
